<?php
    
?>
<table border="1">
    <tr>
        <th>Code</th>
        <th>Author</th>
        <th>Price</th>
        <th>Scores</th>
    </tr>

    <?php foreach ($projects as $project): ?>
        <tr>
            <td><?= $project['code']; ?></td>
            <td><?= $project['author']; ?></td>
            <td><?= $project['price']; ?> грн</td>
            <td><?= implode(',', $project['score']); ?></td>
        </tr>
    <?php endforeach; ?>
</table>














































































