<br />
<br />

<h2>Редагування товару</h2>
<form method="POST">
    <label for="id">ID</label>
    <input id="id" name="id" type="number" min="0" required="true"><br />

    <label for="name">Назва</label>
    <input id="name" name="name" type="text" minlength="4" required="true"><br />

    <label for="country">Країна виробника</label>
    <input id="country" name="country" type="text" minlength="4" required="true"><br />

    <label for="price">Ціна</label>
    <input id="price" name="price" type="number" min="1" required="true"><br />

    <button name="edit_project" type="submit">Edit</button>
</form>
