<?php
?>

<table border="2">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Country</th>
        <th>Price</th>
    </tr>
    <?php foreach ($products as $product): ?>
        <tr>
            <td><?= $product['id']; ?></td>
            <td><?= $product['name']; ?></td>
            <td><?= $product['country']; ?></td>
            <td><?= $product['price']; ?></td>
        </tr>
    <?php endforeach; ?>
</table>
