<br />
<br />

<form method="GET">
    <span>Запит проектів, кошторис яких не більше у <input name="max_price" type="number"> грн.</span> <br/>
    <span>які у трьох номінаціях у сумі набрали не менше, ніж <input name="min_sum_scores" type="number"> балів</span>
    <button type="submit">Отримати</button>
</form>

<h2>Add</h2>
<form method="POST">
    <label for="code">Code</label>
    <input id="code" name="code" type="number" min="0" required="true"><br />

    <label for="fullName">Author</label>
    <input id="author" name="author" type="text" minlength="4" required="true"><br />

    <label for="price">Price</label>
    <input id="price" name="price" type="number" min="1" required="true"><br />

    <label for="scores">3 Scores</label>
    <input id="scores" name="scores" type="text" minlength="5" maxlength="5" required="true"><br />

    <button name="add_project" type="submit">Add</button>
</form>

<h2>Edit</h2>
<form method="POST">
    <label for="code">Code</label>
    <input id="code" name="code" type="number" min="0" required="true"><br />

    <label for="fullName">Author</label>
    <input id="author" name="author" type="text" minlength="4" required="true"><br />

    <label for="price">Price</label>
    <input id="price" name="price" type="number" min="1" required="true"><br />

    <label for="scores">3 Scores</label>
    <input id="scores" name="scores" type="text" minlength="5" maxlength="5" required="true"><br />

    <button name="edit_project" type="submit">Edit</button>
</form>





















































































